cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(route='', view=views.cart_detail, name='cart_detail'),
    path(route='add/<int:product_id>/', view=views.cart_add, name='cart_add'),
    path(
        route='remove/<int:product_id>/',
        view=views.cart_remove,
        name='cart_remove'
    ),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks


urlpatterns = i18n_patterns(
    path(route='admin/', view=admin.site.urls),
    path(route=_('cart/'), view=include('cart.urls', namespace='cart')),
    path(route=_('orders/'), view=include('orders.urls', namespace='orders')),
    path(route=_('payment/'), view=include('payment.urls', namespace='payment')),
    path(route=_('coupons/'), view=include('coupons.urls', namespace='coupons')),
    path(route='rosetta/', view=include('rosetta.urls')),
    path(route='', view=include('shop.urls', namespace='shop')),

)

urlpatterns += [
    path(
        route='payment/webhook/',
        view=webhooks.stripe_webhook,
        name='stripe-webhook'
    ),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path(route='', view=views.product_list, name='product_list'),
    path(
        route='<slug:category_slug>/',
        view=views.product_list,
        name='product_list_by_category'
    ),
    path(
        route='<int:id>/<slug:slug>/',
        view=views.product_detail,
        name='product_detail'
    ),
]

shop/models.py
from django.db import models
from django.urls import reverse
from parler.models import TranslatableModel, TranslatedFields

# Create your models here.


class Category(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200),
        slug=models.SlugField(max_length=200, unique=True),
    )

    class Meta:
        # ordering = ['name']
        # indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])


class Product(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=200),
        slug=models.SlugField(max_length=200),
        description=models.TextField(blank=True),
    )
    category = models.ForeignKey(
        to=Category,
        related_name='products',
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        # ordering = ['name']
        indexes = [
            # models.Index(fields=['id', 'slug']),
            # models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Product, Category
from cart.forms import CartAddProductForm
from .recommender import Recommender
# Create your views here.


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        language = request.LANGUAGE_CODE
        category = get_object_or_404(
            klass=Category, translations__language_code=language, translations__slug=category_slug)
        products = products.filter(category=category)

    return render(
        request=request,
        template_name='shop/product/list.html',
        context={
            'category': category,
            'categories': categories,
            'products': products,
        }
    )


def product_detail(request, id, slug):
    language = request.LANGUAGE_CODE
    product = get_object_or_404(
        klass=Product,
        id=id,
        translations__language_code=language,
        translations__slug=slug,
        available=True
    )
    cart_product_form = CartAddProductForm()
    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(
        request=request,
        template_name='shop/product/detail.html',
        context={'product': product, 'cart_product_form': cart_product_form,
                 'recommended_products': recommended_products}
    )

shop/templates/shop/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="django ecommerce project">
        <meta name="keywords" content="ecommerce django project">
        <title>
            {% block title %}
                {% trans "My Shop" %}
            {% endblock title %}
        </title>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static "favicon_io/apple-touch-icon.png" %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon_io/favicon-32x32.png" %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon_io/favicon-16x16.png" %}">
        <link rel="manifest" href="{% static "favicon_io/site.webmanifest" %}">
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

        <link rel="stylesheet" href="{% static "css/base.css" %}">
    </head>
    <body>
        <div id="header">
            <a href="{% url "shop:product_list" %}" class="logo">{% trans "My Shop" %}</a>
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <div class="languages">
                <p>{% trans "Language" %}:</p>
                <ul class="languages">
                    {% for language in languages %}
                        <li>
                            <a href="/{{ language.code }}/"
                               {% if language.code == LANGUAGE_CODE %}class="selected"{% endif %}>{{ language.name_local }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        {% trans "Your cart" %}:
                        <a href="{% url "cart:cart_detail" %}">
                            {% blocktrans with total=cart.get_total_price count item=total_items %}
                                {{ items }} item, GH₵{{total}}
                            {%plural%}
                                {{items}} items, GH₵{{total}}
                            {% endblocktrans %}
                        </a>
                    {% elif not order %}
                        {% trans "Your cart is empty." %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>