cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path(route='', view=views.cart_detail, name='cart_detail'),
    path(route='add/<int:product_id>/', view=views.cart_add, name='cart_add'),
    path(
        route='remove/<int:product_id>/',
        view=views.cart_remove,
        name='cart_remove'
    ),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

from payment import webhooks


urlpatterns = i18n_patterns(
    path(route='admin/', view=admin.site.urls),
    path(route=_('cart/'), view=include('cart.urls', namespace='cart')),
    path(route=_('orders/'), view=include('orders.urls', namespace='orders')),
    path(route=_('payment/'), view=include('payment.urls', namespace='payment')),
    path(route=_('coupons/'), view=include('coupons.urls', namespace='coupons')),
    path(route='rosetta/', view=include('rosetta.urls')),
    path(route='', view=include('shop.urls', namespace='shop')),

)

urlpatterns += [
    path(
        route='payment/webhook/',
        view=webhooks.stripe_webhook,
        name='stripe-webhook'
    ),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

payment/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

app_name = 'payment'

urlpatterns = [
    path(route=_('process/'), view=views.payment_process, name='process'),
    path(route=_('completed/'), view=views.payment_completed, name='completed'),
    path(route=_('canceled/'), view=views.payment_canceled, name='canceled'),
]

payment/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.conf import settings
from django.http import HttpResponse
import stripe
from decimal import Decimal

from orders.models import Order

# create the Stripe instance.
stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION

# Create your views here.


def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(klass=Order, id=order_id)

    if request.method == 'POST':
        if 'submit_action' in request.POST:
            action = request.POST['submit_action']

            if action.lower() == 'pay with card':
                success_url = request.build_absolute_uri(
                    reverse('payment:completed'))
                cancel_url = request.build_absolute_uri(
                    reverse('payment:canceled'))

                # stripe checkout session data
                session_data = {
                    'mode': 'payment',
                    'client_reference_id': order.id,
                    'success_url': success_url,
                    'cancel_url': cancel_url,
                    'line_items': []
                }

                # add order items to the stripe checkout session
                for item in order.items.all():
                    session_data['line_items'].append({
                        'price_data': {
                            'unit_amount': int(item.price * Decimal('100')),
                            'currency': 'usd',
                            'product_data': {
                                'name': item.product.name,
                            },
                        },
                        'quantity': item.quantity,
                    })

                # stripe coupon
                if order.coupon:
                    stripe_coupon = stripe.Coupon.create(
                        name=order.coupon.code,
                        percent_off=order.discount,
                        duration='once'
                    )
                    session_data['discounts'] = [{
                        'coupon': stripe_coupon.id
                    }]

                # create Stripe checkout session
                session = stripe.checkout.Session.create(**session_data)

                # redirect to Stripe payment form
                return redirect(to=session.url, code=303)

            elif action.lower() == 'pay with momo':
                return HttpResponse('working on it')

    else:
        return render(request=request, template_name='payment/process.html', context=locals())


def payment_completed(request):
    return render(request=request, template_name='payment/completed.html')


def payment_canceled(request):
    return render(request=request, template_name='payment/canceled.html')

payment/templates/payment/canceled.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Payment canceled" %}
{% endblock title %}

{% block content %}
    <h1>{% trans "Your payment has not been processed" %}</h1>
    <p>{% trans "There was a problem processing your payment." %}</p>
{% endblock content %}

payment/templates/payment/completed.html
{% extends "shop/base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Payment successful" %}
{% endblock title %}

{% block content %}
    <h1>{% trans "Your payment was successful" %}</h1>
    <p>{% trans "Your payment has been processed successfully." %}</p>
{% endblock content %}

payment/templates/payment/process.html
{% extends "shop/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
    {% trans "Pay your order" %}
{% endblock title %}

{% block content %}
    <h1>{% trans "Order summary" %}</h1>
    <table class="cart">
        <thead>
            <tr>
                <th>{% trans "Image" %}</th>
                <th>{% trans "Product" %}</th>
                <th>{% trans "Price" %}</th>
                <th>{% trans "Quantity" %}</th>
                <th>{% trans "Total" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for item in order.items.all %}
                <tr class="row{% cycle "1" "2" %}">
                    <td>
                        <img src="{% if item.product.image %}{{ item.product.image.url }}{% else %}{% static "img/no_img.png" %}{% endif %}" alt="{{ product.name }} image">
                        <td>{{ item.product.name }}</td>
                        <td>GH₵{{ item.price }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>GH₵{{ item.get_cost }}</td>
                    </td>
                </tr>
            {% endfor %}
            {% if order.coupon %}
                <tr class="subtotal">
                    <td>{% trans "Subtotal" %}</td>
                    <td colspan="3"></td>
                    <td>GH₵{{ order.get_total_cost_before_discount|floatformat:2 }}</td>
                </tr>
                <tr>
                    <td>
                        {% blocktrans with code=order.coupon.code discount=order.discount %}
                            "{{ code }}" ({{ discount }}% off)
                        {% endblocktrans %}
                    </td>
                    <td colspan="3"></td>
                    <td class="neg">- GH₵{{ order.get_discount|floatformat:2 }}</td>
                </tr>
            {% endif %}
            <tr class="total">
                <td>{% trans "Total" %}</td>
                <td colspan="3"></td>
                <td>GH₵{{ order.get_total_cost|floatformat:2 }}</td>
            </tr>
        </tbody>
    </table>
    <form action="{% url "payment:process" %}" method="post">
        <input type="submit"
               name="submit_action"
               value="{% trans "Pay with card" %}">
        <input type="submit"
               name="submit_action"
               value="{% trans "Pay with momo" %}">
        {% csrf_token %}
    </form>
{% endblock content %}